config/routes.rb
Rails.application.routes.draw do
  get 'index', to: 'pages#index'
  get 'dashboard', to: 'pages#dashboard'
  get 'create', to: 'pages#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true



end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :state, presence: true

    
    scope :find_valid, -> { where("state = ?", 'En Proceso')}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard

  
  def dashboard
    if params[:state].present?
      @projects = Project.where('state = ?', params[:state])
    else 
      @projects = Project.find_valid
    end 
  end

  def index
    @project = Project.new
  end
  

  def create
      @project = Project.create(name: params[:name],
      description: params[:description],
      started_at: params[:started_at],
      finished_at: params[:finished_at],
      state: params[:state])   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestProy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="container">
      <%= yield %>
    </div>



    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/create.html.erb
<% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited this user from being saved:
        </h2>
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% else %>
    <h1> Se creó tu Proyecto con éxito </h1>
<% end %>

app/views/pages/dashboard.html.erb
<h1>Mis Proyectos</h1>

<table class ='table'>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Fecha de Partida</th>
            <th>Fecha de Término</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody>
        
        <% @projects.each do |p| %>
        <tr>
            <td><%= p.name %></td>
            <td><%= p.description %></td>
            <td><%= p.started_at %></td>
            <td><%= p.finished_at %></td>
            <td><%= p.state %></td>
        </tr>
        <% end %>
        
    </tbody>
</table>



app/views/pages/index.html.erb
<h1>Crea tu Proyecto</h1>

<form method="get" action="create" id="create_project">

    <div class="form-group">
        <label for="name">Nombre</label>
        <input name= "name" type="text" class="form-control" id="name" ariadescribedby="
        emailHelp" placeholder="">
    </div>

    <div class="form-group">
        <label for="description">Descripción</label>
        <textarea name="description" class="form-control"> </textarea>
    </div>

    <div class="form-group">
        <label for="started_at">Fecha de Inicio</label>
        <input name= "started_at" type="date" class="form-control"  ariadescribedby="
        emailHelp" placeholder="">
    </div>
    <br>
    <div class="form-group">
        <label for="finished_at">Fecha de Término</label>
        <input name= "finished_at" type="date" class="form-control"  ariadescribedby="
        emailHelp" placeholder="">
    </div>  
    <br>
    <div>
        <div><label for="state">Estado del Proyecto</label></div>
        <div><select id="state" name="state">
            <option selected="selected" value="Propuesta">Propuesta</option>
            <option value="En Proceso">En Proceso</option>
            <option value="Finalizado">Finalizado</option>
            </select></div>
    </div>  
    <br>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
    

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <%= link_to 'Home', root_path, class: 'navbar-brand' %>
            </li>

            <li class="nav-item">
                <%= link_to 'Dashboard', dashboard_path, class: 'navbar-brand' %>
            </li>
        
        </ul>
    </div>

    <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="state">
        <button class="btn btn-outline-success my-2 my-sm-0"
        type="submit">Search</button>
</form>

    
</nav>